version: '3'
services:
  voting-back:
    container_name: "voting-back"
    depends_on:
      - voting-db
    build: ./backend/
    ports:
     - "8000:8000"
    volumes:
     - ./backend/app/:/opt/app
    links:
     - voting-db
  voting-db:
    container_name: "voting-db"
    build: ./mysql/
    ports:
     - "3306:3306"
    volumes:
     - ./mysql/data/:/var/lib/mysql
     - ./mysql/conf/:/conf
  voting-ui:
    container_name: "voting-ui"
    depends_on:
      - voting-back
    links:
     - voting-back  
    build: ./ui/
    ports:
     - "4200:4200"
    volumes:
     - ./ui/src/:/app/my-project/src
